version: 2.1

jobs:
  release:
    docker:
      - image: circleci/node:24
    steps:
      - checkout
      - run:
          name: Create config.json
          command: echo "$CONFIG_SECRET" > ./config.json
      - run:
          name: Install dependencies
          command: npm install runship
      - run:
          name: Run index.js
          command: node index.js

workflows:
  version: 2
  release_workflow:
    jobs:
      - release